apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "emqx.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "emqx.name" . }}
    helm.sh/chart: {{ include "emqx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  "emqx_prometheus.conf": |
    ##--------------------------------------------------------------------
    ## emqx_prometheus for EMQX
    ##--------------------------------------------------------------------

    ## The Prometheus Push Gateway URL address
    ##
    ## Note: You can comment out this line to disable it
    prometheus.push.gateway.server = {{ .Values.emqxPromethues.pushgateway }}

    ## The metrics data push interval (millisecond)
    ##
    ## Default: 15000
    prometheus.interval = {{ .Values.emqxPromethues.interval }}