{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "emqx.fullname" . }}-basic-auth
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
stringData:
  {{- if not (empty .Values.emqxConfig.EMQX_MANAGEMENT__DEFAULT_APPLICATION__ID) }}
  username: admin
  {{- else }}
  username: {{ .Values.emqxConfig.EMQX_MANAGEMENT__DEFAULT_APPLICATION__ID }}
  {{- end }}
  {{- if not (empty .Values.emqxConfig.EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET) }}
  password: public
  {{- else }}
  password: {{ .Values.emqxConfig.EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET}}
  {{- end }}
{{- end }}